Draft: OpenAPI 3.1.0 Documentation Generation
Ge0rg3/flask-parameter-validation pull request #42
Opened 2024-06-18 03:55 UTC by smt5541

2024-10-15 22:55 UTC, Ge0rg3 requested changes

2024-10-15 22:55 UTC, Ge0rg3 commented on flask_parameter_validation/docs_blueprint.py
> +def generate_openapi_paths_object():
Please can we add some comments/spacing to this function? It is quite tricky to understand the flow atm. Otherwise looks great!

2025-08-04 12:30 UTC, Ge0rg3 commented
Hi @smt5541, is this good to resolve/merge?

2025-11-20 16:30 UTC, smt5541 commented
Now pending implementation of TypedDict support

2026-05-28 14:56 UTC, merged