Add support for standard list type hints
Ge0rg3/flask-parameter-validation pull request #50
Opened 2024-07-01 23:42 UTC by smt5541

### 🛠 Changes being made

#### Give examples of the changes you've made in this pull request. Include an itemized list if you can.

- Update `ValidateParameters#__call__` and `ValidateParameters#validate` to support `list` alongside the existing support for `typing.List`
- Update GitHub Actions to run tests on Python 3.9-3.12

### 🧠 Rationale behind the change

#### Why did you choose to make these changes?

Reading through the `typing` documentation, I noticed that `typing.List` was deprecated as of Python 3.9. Since this library currently targets Python 3.11 at a minimum (as of 

#### Does this pull request resolve any open issues?

Closes #48 

#### Were there any trade-offs you had to consider?

I had to ensure that our minimum supported Python version would not be changed by implementing this support. Our dependencies pin us to a minimum of Python 3.9, so it seems we remain at that level.

### 🧪 Testing

- [X] Have tests been added or updated for the changes introduced in this pull request?

- [X] Are the changes backwards compatible?

#### If the changes aren't backwards compatible, what other options were explored?

### ✨ Quality check

- [X] Are your changes free of any erroneous print statements, debuggers or other leftover code?

- [X] Has the README been updated to reflect the changes introduced (if applicable)?

### 💬 Additional comments

#### Feel free to add any further information below

Depends on #45

2024-07-11 17:00 UTC, Ge0rg3 requested changes

2024-07-11 22:19 UTC, smt5541 commented
> I think to resolve current conflicts we can just take this branch version as source of truth?

Eh, mostly - some indentations introduced in other PRs made it a little messier, but that's all set now

2024-07-13 23:23 UTC, Ge0rg3 approved these changes

2024-07-13 23:23 UTC, merged

2024-07-13 23:24 UTC, Ge0rg3 commented
Btw love the added pypi classifiers on this, should help with project visibility 👍